services:
    devcontainer:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        ports:
            - "8443:8443"
        networks:
            - devcon
        volumes:
            - ..:/workspace

networks:
    devcon:
        name: devcon
